Repository JamesTiberiusKirk/team5agile, pull requests merged in 2020-02, with the labels that each got.

#9 Server code refactor
  Software_Code/backend/db/db.js
  Software_Code/backend/main.js
  Software_Code/backend/routes/index.js
  Software_Code/backend/server.js
Labels: enhancement

#10 Tests
  Software_Code/backend/package-lock.json
  Software_Code/backend/package.json
  Software_Code/backend/test/api.test.js
  Software_Code/backend/tests/api.test.js
Labels: feature request

#11 Added pagination procedure
  Software_Code/backend/README.md
  Software_Code/backend/db/SQL_Statements/procedures/sortOptionsPages.sql
Labels: code review, documentation

#12 Documentation
  Product_Backlog/product backlog.xlsx
  Sprint_1/README.md
  Sprint_1/Sprint_Retrospective/Sprint Retrospective.docx
  Sprint_1/Sprint_Review/sprint review.docx
  Sprint_2/README.md
  Sprint_2/Sprint_Backlog/SprintBacklog2.xlsx
Labels: documentation

#23 Disatace search
  Software_Code/backend/README.md
  Software_Code/backend/lib/DistanceCalculator.js
  Software_Code/backend/routes/index.js
  Software_Code/backend/test/api.test.js
Labels: documentation, feature request

#26 Documentation
  Sprint_2/README.md
  Sprint_2/Sprint_Backlog/SprintBacklog2.xlsx
  Sprint_2/Sprint_Retrospective/Actions from Sprint 1 Retrospective.docx
Labels: documentation

#27 Distace search
  Software_Code/backend/test/mocha.opts
Labels: bug-fix

#28 Distace search
  Software_Code/backend/README.md
  Software_Code/backend/routes/index.js
  Software_Code/backend/test/api.test.js
  Software_Code/backend/test/data_examples/procedures.js
Labels: documentation, enhancement, feature request

#29 Added a port nr to server constructor
  Software_Code/backend/main.js
  Software_Code/backend/server.js
  Software_Code/backend/test/api.test.js
Labels: enhancement

#32 Added Database Joins
  Software_Code/backend/db/SQL_Statements/views/options.sql
Labels: code review
